### ISSUE TITLE
TypeError: transport is not a function

### ISSUE THREAD

**Issue by f3ist** [fanout/node-pubcontrol#2]
Error publishing TypeError: transport is not a function
at Object.performHttpRequest (/var/task/webpack:/builds/jetclosing/jetCloudServerComponents/node_modules/pubcontrol/lib/pubcontrolclient.js:103:1)
at Object.startPubCall (/var/task/webpack:/builds/jetclosing/jetCloudServerComponents/node_modules/pubcontrol/lib/pubcontrolclient.js:96:1)
at Object.publish (/var/task/webpack:/builds/jetclosing/jetCloudServerComponents/node_modules/pubcontrol/lib/pubcontrolclient.js:57:1)
at /var/task/webpack:/builds/jetclosing/jetCloudServerComponents/node_modules/pubcontrol/lib/pubcontrol.js:81:1
at Array.forEach (<anonymous>)
at utilities.defineClass.removeAllClients.clients.publish (/var/task/webpack:/builds/jetclosing/jetCloudServerComponents/node_modules/pubcontrol/lib/pubcontrol.js:80:1)
at utilities.defineClass.applyGripConfig.pubControl.publish (/var/task/webpack:/builds/jetclosing/jetCloudServerComponents/node_modules/grip/lib/grippubcontrol.js:79:1)

**Comment by jkarneges** [comment]
Hmm, what environment is this being executed in?

The code was recently changed to use `fetch` instead of using Node's `http` module directly. If `fetch` is available then it is used. If not, the `node-fetch` module is used which wraps Node's `http`.

It's possible there's something wrong with the check near the top of pubcontrolclient.js but I'm not sure what it would be.

**Comment by f3ist** [comment]
@jkarneges We're using this in AWS node 8.10

**Comment by jkarneges** [comment]
Works fine over here using Lambda with Node 8.10. I wonder if some other package is conflicting. Can you share the output of `npm list` ?

**Comment by f3ist** [comment]
@jkarneges I did depth 0, see below. Maybe another lib is setting the `fetch` var?
```
├── @google-cloud/storage@1.7.0
├── aws-cloudfront-sign@2.2.0
├── aws-sdk@2.189.0
├── aws4@1.6.0
├── azure-ad-jwt@1.1.0
├── babel-core@6.26.0
├── babel-jest@22.4.1
├── babel-loader@7.1.4
├── babel-plugin-js-logger@1.0.17
├── babel-plugin-source-map-support@2.0.1
├── babel-plugin-transform-builtin-extend@1.1.2
├── babel-plugin-transform-decorators-legacy@1.3.4
├── babel-plugin-transform-runtime@6.23.0
├── babel-polyfill@6.26.0
├── babel-preset-env@1.7.0
├── babel-preset-flow@6.23.0
├── babel-preset-stage-2@6.24.1
├── babel-runtime@6.11.6
├── base64-loader@1.0.0
├── clean-deep@3.0.2
├── currency-formatter@1.3.2
├── deep-equal@1.0.1
├── faas-grip@1.0.1
├── fcm-node@1.0.16
├── flow-bin@0.59.0
├── flow-coverage-report@0.4.0
├── handlebars@4.0.11
├── imagemagick@0.1.3
├── immutable@4.0.0-rc.9
├── jest@22.4.2
├── js-logger@1.4.1
├── json-loader@0.5.7
├── jsonwebtoken@7.4.3
├── lodash.merge@4.6.1
├── madison@1.0.2
├── mandrill-api@1.0.45
├── md5@2.2.1
├── moment@2.20.1
├── node-rsa@0.4.2
├── node-vault@0.6.1
├── nodemailer@4.4.2
├── null-prune@1.0.3
├── pdfcrowd@4.3.0
├── promise-settle@0.3.0
├── raw-loader@0.5.1
├── serverless@1.26.1
├── serverless-plugin-bind-deployment-id@1.0.1
├── serverless-plugin-lambda-dead-letter@1.2.1
├── serverless-webpack@5.1.1
├── shallowequal@1.0.2
├── source-map-support@0.5.6
├── string-natural-compare@2.0.2
├── unirest@0.5.1
├── uuid@3.2.1
├── webpack@4.2.0
├── xml-loader@1.2.1
├── xml2js@0.4.19
├── xmldom@0.1.27
└── xpath@0.0.23
```

**Comment by jkarneges** [comment]
Probably need to see the rest of the tree. My guess is it would be in a dependency, like isomorphic-fetch (but that shouldn't be a problem...). You could also grep the node_modules for references to fetch.

**Comment by jkarneges** [comment]
It would also be nice to know what type `fetch` is for you. Presuming it's global, you could console.log(typeof fetch) to see.

**Comment by f3ist** [comment]
@jkarneges Alright, here is the whole prod tree. Also, it works when invoking the lambda locally, just not when its invoked in the cloud, which leads me to believe its related to the node environment.
```
├─┬ @google-cloud/storage@1.7.0
│ ├─┬ @google-cloud/common@0.17.0
│ │ ├── array-uniq@1.0.3
│ │ ├── arrify@1.0.1 deduped
│ │ ├── concat-stream@1.6.1 deduped
│ │ ├── create-error-class@3.0.2 deduped
│ │ ├── duplexify@3.5.4 deduped
│ │ ├── ent@2.2.0
│ │ ├── extend@3.0.1 deduped
│ │ ├─┬ google-auto-auth@0.10.1
│ │ │ ├── async@2.6.0 deduped
│ │ │ ├─┬ gcp-metadata@0.6.3
│ │ │ │ ├─┬ axios@0.18.0
│ │ │ │ │ ├─┬ follow-redirects@1.5.0
│ │ │ │ │ │ └─┬ debug@3.1.0
│ │ │ │ │ │   └── ms@2.0.0
│ │ │ │ │ └── is-buffer@1.1.6
│ │ │ │ ├── extend@3.0.1 deduped
│ │ │ │ └── retry-axios@0.3.2
│ │ │ ├─┬ google-auth-library@1.5.0
│ │ │ │ ├── axios@0.18.0 deduped
│ │ │ │ ├── gcp-metadata@0.6.3 deduped
│ │ │ │ ├─┬ gtoken@2.3.0
│ │ │ │ │ ├── axios@0.18.0 deduped
│ │ │ │ │ ├─┬ google-p12-pem@1.0.2
│ │ │ │ │ │ ├── node-forge@0.7.4
│ │ │ │ │ │ └── pify@3.0.0
│ │ │ │ │ ├── jws@3.1.4 deduped
│ │ │ │ │ ├── mime@2.3.1 deduped
│ │ │ │ │ └── pify@3.0.0
│ │ │ │ ├── jws@3.1.4 deduped
│ │ │ │ ├── lodash.isstring@4.0.1 deduped
│ │ │ │ ├─┬ lru-cache@4.1.3
│ │ │ │ │ ├── pseudomap@1.0.2
│ │ │ │ │ └── yallist@2.1.2
│ │ │ │ └── retry-axios@0.3.2 deduped
│ │ │ └── request@2.83.0 deduped
│ │ ├── is@3.2.1 deduped
│ │ ├── log-driver@1.2.7
│ │ ├── methmeth@1.1.0
│ │ ├── modelo@4.2.3
│ │ ├── request@2.83.0 deduped
│ │ ├─┬ retry-request@3.3.1
│ │ │ ├── request@2.83.0 deduped
│ │ │ └── through2@2.0.3 deduped
│ │ ├─┬ split-array-stream@1.0.3
│ │ │ ├── async@2.6.0 deduped
│ │ │ └── is-stream-ended@0.1.4
│ │ ├── stream-events@1.0.4 deduped
│ │ ├── string-format-obj@1.1.1
│ │ └── through2@2.0.3 deduped
│ ├── arrify@1.0.1
│ ├─┬ async@2.6.0
│ │ └── lodash@4.17.5
│ ├─┬ compressible@2.0.13
│ │ └── mime-db@1.33.0
│ ├─┬ concat-stream@1.6.1
│ │ ├── inherits@2.0.3
│ │ ├─┬ readable-stream@2.3.4
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.3
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@2.0.0
│ │ │ ├── safe-buffer@5.1.1
│ │ │ ├─┬ string_decoder@1.0.3
│ │ │ │ └── safe-buffer@5.1.1
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ create-error-class@3.0.2
│ │ └── capture-stack-trace@1.0.0
│ ├─┬ duplexify@3.5.4
│ │ ├─┬ end-of-stream@1.4.1
│ │ │ └─┬ once@1.4.0
│ │ │   └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├── readable-stream@2.3.4 deduped
│ │ └── stream-shift@1.0.0
│ ├── extend@3.0.1
│ ├─┬ gcs-resumable-upload@0.10.2
│ │ ├─┬ configstore@3.1.2
│ │ │ ├─┬ dot-prop@4.2.0
│ │ │ │ └── is-obj@1.0.1
│ │ │ ├── graceful-fs@4.1.11
│ │ │ ├─┬ make-dir@1.2.0
│ │ │ │ └── pify@3.0.0
│ │ │ ├─┬ unique-string@1.0.0
│ │ │ │ └── crypto-random-string@1.0.0
│ │ │ ├─┬ write-file-atomic@2.3.0
│ │ │ │ ├── graceful-fs@4.1.11
│ │ │ │ ├── imurmurhash@0.1.4
│ │ │ │ └── signal-exit@3.0.2
│ │ │ └── xdg-basedir@3.0.0 deduped
│ │ ├── google-auto-auth@0.10.1 deduped
│ │ ├─┬ pumpify@1.4.0
│ │ │ ├── duplexify@3.5.4 deduped
│ │ │ ├── inherits@2.0.3
│ │ │ └── pump@2.0.1 deduped
│ │ ├─┬ request@2.87.0
│ │ │ ├── aws-sign2@0.7.0 deduped
│ │ │ ├── aws4@1.6.0 deduped
│ │ │ ├── caseless@0.12.0 deduped
│ │ │ ├── combined-stream@1.0.5 deduped
│ │ │ ├── extend@3.0.1 deduped
│ │ │ ├── forever-agent@0.6.1 deduped
│ │ │ ├── form-data@2.3.1 deduped
│ │ │ ├── har-validator@5.0.3 deduped
│ │ │ ├── http-signature@1.2.0 deduped
│ │ │ ├── is-typedarray@1.0.0 deduped
│ │ │ ├── isstream@0.1.2 deduped
│ │ │ ├── json-stringify-safe@5.0.1 deduped
│ │ │ ├── mime-types@2.1.17 deduped
│ │ │ ├── oauth-sign@0.8.2 deduped
│ │ │ ├── performance-now@2.1.0 deduped
│ │ │ ├── qs@6.5.1 deduped
│ │ │ ├── safe-buffer@5.1.1 deduped
│ │ │ ├── tough-cookie@2.3.3 deduped
│ │ │ ├── tunnel-agent@0.6.0 deduped
│ │ │ └── uuid@3.2.1 deduped
│ │ └── stream-events@1.0.4 deduped
│ ├─┬ hash-stream-validation@0.2.1
│ │ └── through2@2.0.3 deduped
│ ├── is@3.2.1
│ ├── mime@2.3.1
│ ├─┬ mime-types@2.1.17
│ │ └── mime-db@1.30.0
│ ├─┬ once@1.4.0
│ │ └── wrappy@1.0.2
│ ├─┬ pumpify@1.5.1
│ │ ├─┬ duplexify@3.6.0
│ │ │ ├── end-of-stream@1.4.1 deduped
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── readable-stream@2.3.4 deduped
│ │ │ └── stream-shift@1.0.0 deduped
│ │ ├── inherits@2.0.3
│ │ └─┬ pump@2.0.1
│ │   ├── end-of-stream@1.4.1 deduped
│ │   └─┬ once@1.4.0
│ │     └── wrappy@1.0.2
│ ├─┬ request@2.87.0
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.6.0 deduped
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1 deduped
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.1
│ │ │ ├── asynckit@0.4.0
│ │ │ ├── combined-stream@1.0.5 deduped
│ │ │ └── mime-types@2.1.17 deduped
│ │ ├─┬ har-validator@5.0.3
│ │ │ ├─┬ ajv@5.3.0
│ │ │ │ ├── co@4.6.0
│ │ │ │ ├── fast-deep-equal@1.0.0
│ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ └── json-schema-traverse@0.3.1
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   ├── assert-plus@1.0.0 deduped
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ └─┬ sshpk@1.13.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │   │ └── jsbn@0.1.1 deduped
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├── mime-types@2.1.17 deduped
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.1
│ │ ├── safe-buffer@5.1.1 deduped
│ │ ├─┬ tough-cookie@2.3.3
│ │ │ └── punycode@1.4.1
│ │ ├─┬ tunnel-agent@0.6.0
│ │ │ └── safe-buffer@5.1.1 deduped
│ │ └── uuid@3.2.1 deduped
│ ├── safe-buffer@5.1.1
│ ├── snakeize@0.1.0
│ ├─┬ stream-events@1.0.4
│ │ └── stubs@3.0.0
│ ├─┬ through2@2.0.3
│ │ ├── readable-stream@2.3.4 deduped
│ │ └── xtend@4.0.1
│ └── xdg-basedir@3.0.0
├─┬ aws-cloudfront-sign@2.2.0
│ └── lodash@3.10.1
├─┬ aws-sdk@2.189.0
│ ├─┬ buffer@4.9.1
│ │ ├── base64-js@1.2.1
│ │ ├── ieee754@1.1.8
│ │ └── isarray@1.0.0
│ ├── events@1.1.1
│ ├── jmespath@0.15.0
│ ├── querystring@0.2.0
│ ├── sax@1.2.1
│ ├─┬ url@0.10.3
│ │ ├── punycode@1.3.2
│ │ └── querystring@0.2.0 deduped
│ ├── uuid@3.1.0
│ ├─┬ xml2js@0.4.17
│ │ ├── sax@1.2.1 deduped
│ │ └── xmlbuilder@4.2.1 deduped
│ └─┬ xmlbuilder@4.2.1
│   └── lodash@4.17.5 deduped
├── aws4@1.6.0
├─┬ azure-ad-jwt@1.1.0
│ ├─┬ jsonwebtoken@8.1.0
│ │ ├─┬ jws@3.1.4
│ │ │ ├── base64url@2.0.0
│ │ │ ├─┬ jwa@1.1.5
│ │ │ │ ├── base64url@2.0.0 deduped
│ │ │ │ ├── buffer-equal-constant-time@1.0.1
│ │ │ │ ├─┬ ecdsa-sig-formatter@1.0.9
│ │ │ │ │ ├── base64url@2.0.0 deduped
│ │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── safe-buffer@5.1.1 deduped
│ │ ├── lodash.includes@4.3.0
│ │ ├── lodash.isboolean@3.0.3
│ │ ├── lodash.isinteger@4.0.4
│ │ ├── lodash.isnumber@3.0.3
│ │ ├── lodash.isplainobject@4.0.6
│ │ ├── lodash.isstring@4.0.1
│ │ ├── lodash.once@4.1.1
│ │ ├── ms@2.0.0
│ │ └── xtend@4.0.1
│ └─┬ request@2.83.0
│   ├── aws-sign2@0.7.0 deduped
│   ├── aws4@1.6.0 deduped
│   ├── caseless@0.12.0 deduped
│   ├── combined-stream@1.0.5 deduped
│   ├── extend@3.0.1 deduped
│   ├── forever-agent@0.6.1 deduped
│   ├── form-data@2.3.1 deduped
│   ├── har-validator@5.0.3 deduped
│   ├─┬ hawk@6.0.2
│   │ ├─┬ boom@4.3.1
│   │ │ └── hoek@4.2.0
│   │ ├─┬ cryptiles@3.1.2
│   │ │ └─┬ boom@5.2.0
│   │ │   └── hoek@4.2.0
│   │ ├── hoek@4.2.0
│   │ └─┬ sntp@2.1.0
│   │   └── hoek@4.2.0
│   ├── http-signature@1.2.0 deduped
│   ├── is-typedarray@1.0.0 deduped
│   ├── isstream@0.1.2 deduped
│   ├── json-stringify-safe@5.0.1 deduped
│   ├── mime-types@2.1.17 deduped
│   ├── oauth-sign@0.8.2 deduped
│   ├── performance-now@2.1.0 deduped
│   ├── qs@6.5.1 deduped
│   ├── safe-buffer@5.1.1 deduped
│   ├── stringstream@0.0.5
│   ├── tough-cookie@2.3.3 deduped
│   ├── tunnel-agent@0.6.0 deduped
│   └── uuid@3.2.1 deduped
├─┬ babel-runtime@6.11.6
│ ├── core-js@2.5.3
│ └── regenerator-runtime@0.9.6
├── base64-loader@1.0.0
├─┬ clean-deep@3.0.2
│ ├── lodash.isempty@4.4.0
│ ├── lodash.isplainobject@4.0.6
│ └── lodash.transform@4.6.0
├── deep-equal@1.0.1
├─┬ faas-grip@1.0.1
│ ├─┬ grip@1.2.8
│ │ ├── jwt-simple@0.5.1
│ │ └─┬ pubcontrol@1.2.0
│ │   ├── agentkeepalive@2.2.0
│ │   ├── jwt-simple@0.5.1 deduped
│ │   └── node-fetch@2.1.2
│ └── jspack@0.0.4
├─┬ fcm-node@1.0.16
│ └── retry@0.9.0
├─┬ handlebars@4.0.11
│ ├── async@1.5.2
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ ├─┬ source-map@0.4.4
│ │ └── amdefine@1.0.1
│ └─┬ uglify-js@2.8.29
│   ├── source-map@0.5.7
│   ├── uglify-to-browserify@1.0.2
│   └─┬ yargs@3.10.0
│     ├── camelcase@1.2.1
│     ├─┬ cliui@2.1.0
│     │ ├─┬ center-align@0.1.3
│     │ │ ├─┬ align-text@0.1.4
│     │ │ │ ├─┬ kind-of@3.2.2
│     │ │ │ │ └── is-buffer@1.1.6
│     │ │ │ ├── longest@1.0.1
│     │ │ │ └── repeat-string@1.6.1
│     │ │ └── lazy-cache@1.0.4
│     │ ├─┬ right-align@0.1.3
│     │ │ └── align-text@0.1.4 deduped
│     │ └── wordwrap@0.0.2
│     ├── decamelize@1.2.0
│     └── window-size@0.1.0
├── imagemagick@0.1.3
├── immutable@4.0.0-rc.9
├── js-logger@1.4.1
├─┬ jsonwebtoken@7.4.3
│ ├─┬ joi@6.10.1
│ │ ├── hoek@2.16.3
│ │ ├── isemail@1.2.0
│ │ ├── moment@2.20.1 deduped
│ │ └─┬ topo@1.1.0
│ │   └── hoek@2.16.3 deduped
│ ├─┬ jws@3.1.4
│ │ ├── base64url@2.0.0
│ │ ├─┬ jwa@1.1.5
│ │ │ ├── base64url@2.0.0 deduped
│ │ │ ├── buffer-equal-constant-time@1.0.1
│ │ │ ├─┬ ecdsa-sig-formatter@1.0.9
│ │ │ │ ├── base64url@2.0.0 deduped
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── safe-buffer@5.1.1 deduped
│ │ └── safe-buffer@5.1.1
│ ├── lodash.once@4.1.1
│ ├── ms@2.1.1
│ └── xtend@4.0.1
├── lodash.merge@4.6.1
├── madison@1.0.2
├── mandrill-api@1.0.45
├─┬ md5@2.2.1
│ ├── charenc@0.0.2
│ ├── crypt@0.0.2
│ └── is-buffer@1.1.6
├── moment@2.20.1
├─┬ node-rsa@0.4.2
│ └── asn1@0.2.3
├─┬ node-vault@0.6.1
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0
│ ├── mustache@2.3.0
│ ├─┬ request@2.83.0
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.6.0 deduped
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.6
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.2
│ │ │ ├── asynckit@0.4.0
│ │ │ ├── combined-stream@1.0.6 deduped
│ │ │ └── mime-types@2.1.18 deduped
│ │ ├─┬ har-validator@5.0.3
│ │ │ ├─┬ ajv@5.5.2
│ │ │ │ ├── co@4.6.0
│ │ │ │ ├── fast-deep-equal@1.1.0
│ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ └── json-schema-traverse@0.3.1
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ hawk@6.0.2
│ │ │ ├─┬ boom@4.3.1
│ │ │ │ └── hoek@4.2.1 deduped
│ │ │ ├─┬ cryptiles@3.1.2
│ │ │ │ └─┬ boom@5.2.0
│ │ │ │   └── hoek@4.2.1 deduped
│ │ │ ├── hoek@4.2.1
│ │ │ └─┬ sntp@2.1.0
│ │ │   └── hoek@4.2.1 deduped
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   ├── assert-plus@1.0.0 deduped
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ └─┬ sshpk@1.13.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │   │ └── jsbn@0.1.1 deduped
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.18
│ │ │ └── mime-db@1.33.0
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.1
│ │ ├── safe-buffer@5.1.1
│ │ ├── stringstream@0.0.5
│ │ ├─┬ tough-cookie@2.3.4
│ │ │ └── punycode@1.4.1
│ │ ├─┬ tunnel-agent@0.6.0
│ │ │ └── safe-buffer@5.1.1 deduped
│ │ └── uuid@3.2.1 deduped
│ ├─┬ request-promise-native@1.0.5
│ │ ├─┬ request-promise-core@1.1.1
│ │ │ └── lodash@4.17.5
│ │ ├── stealthy-require@1.1.1
│ │ └── tough-cookie@2.3.4 deduped
│ └── tv4@1.3.0
├── nodemailer@4.4.2
├── null-prune@1.0.3
├── pdfcrowd@4.3.0
├── promise-settle@0.3.0
├─┬ serverless-plugin-lambda-dead-letter@1.2.1
│ └── bluebird@3.5.1
├── shallowequal@1.0.2
├─┬ source-map-support@0.5.6
│ ├── buffer-from@1.0.0
│ └── source-map@0.6.1
├── string-natural-compare@2.0.2
├─┬ unirest@0.5.1
│ ├─┬ form-data@0.2.0
│ │ ├── async@0.9.2
│ │ ├─┬ combined-stream@0.0.7
│ │ │ └── delayed-stream@0.0.5
│ │ └─┬ mime-types@2.0.14
│ │   └── mime-db@1.12.0
│ ├── mime@1.3.6
│ └─┬ request@2.74.0
│   ├── aws-sign2@0.6.0
│   ├── aws4@1.6.0 deduped
│   ├─┬ bl@1.1.2
│   │ └─┬ readable-stream@2.0.6
│   │   ├── core-util-is@1.0.2
│   │   ├── inherits@2.0.3
│   │   ├── isarray@1.0.0
│   │   ├── process-nextick-args@1.0.7
│   │   ├── string_decoder@0.10.31
│   │   └── util-deprecate@1.0.2
│   ├── caseless@0.11.0
│   ├─┬ combined-stream@1.0.6
│   │ └── delayed-stream@1.0.0
│   ├── extend@3.0.1
│   ├── forever-agent@0.6.1
│   ├─┬ form-data@1.0.1
│   │ ├─┬ async@2.6.0
│   │ │ └── lodash@4.17.5
│   │ ├── combined-stream@1.0.6 deduped
│   │ └── mime-types@2.1.18 deduped
│   ├─┬ har-validator@2.0.6
│   │ ├─┬ chalk@1.1.3
│   │ │ ├── ansi-styles@2.2.1
│   │ │ ├── escape-string-regexp@1.0.5
│   │ │ ├─┬ has-ansi@2.0.0
│   │ │ │ └── ansi-regex@2.1.1
│   │ │ ├─┬ strip-ansi@3.0.1
│   │ │ │ └── ansi-regex@2.1.1 deduped
│   │ │ └── supports-color@2.0.0
│   │ ├── commander@2.14.1
│   │ ├─┬ is-my-json-valid@2.17.2
│   │ │ ├── generate-function@2.0.0
│   │ │ ├─┬ generate-object-property@1.2.0
│   │ │ │ └── is-property@1.0.2
│   │ │ ├── is-my-ip-valid@1.0.0
│   │ │ ├── jsonpointer@4.0.1
│   │ │ └── xtend@4.0.1
│   │ └─┬ pinkie-promise@2.0.1
│   │   └── pinkie@2.0.4
│   ├─┬ hawk@3.1.3
│   │ ├─┬ boom@2.10.1
│   │ │ └── hoek@2.16.3 deduped
│   │ ├─┬ cryptiles@2.0.5
│   │ │ └── boom@2.10.1 deduped
│   │ ├── hoek@2.16.3
│   │ └─┬ sntp@1.0.9
│   │   └── hoek@2.16.3 deduped
│   ├─┬ http-signature@1.1.1
│   │ ├── assert-plus@0.2.0
│   │ ├─┬ jsprim@1.4.1
│   │ │ ├── assert-plus@1.0.0
│   │ │ ├── extsprintf@1.3.0
│   │ │ ├── json-schema@0.2.3
│   │ │ └─┬ verror@1.10.0
│   │ │   ├── assert-plus@1.0.0
│   │ │   ├── core-util-is@1.0.2 deduped
│   │ │   └── extsprintf@1.3.0 deduped
│   │ └─┬ sshpk@1.13.1
│   │   ├── asn1@0.2.3
│   │   ├── assert-plus@1.0.0
│   │   ├─┬ bcrypt-pbkdf@1.0.1
│   │   │ └── tweetnacl@0.14.5 deduped
│   │   ├─┬ dashdash@1.14.1
│   │   │ └── assert-plus@1.0.0
│   │   ├─┬ ecc-jsbn@0.1.1
│   │   │ └── jsbn@0.1.1 deduped
│   │   ├─┬ getpass@0.1.7
│   │   │ └── assert-plus@1.0.0
│   │   ├── jsbn@0.1.1
│   │   └── tweetnacl@0.14.5
│   ├── is-typedarray@1.0.0
│   ├── isstream@0.1.2
│   ├── json-stringify-safe@5.0.1
│   ├─┬ mime-types@2.1.18
│   │ └── mime-db@1.33.0
│   ├── node-uuid@1.4.8
│   ├── oauth-sign@0.8.2
│   ├── qs@6.2.3
│   ├── stringstream@0.0.5
│   ├─┬ tough-cookie@2.3.4
│   │ └── punycode@1.4.1
│   └── tunnel-agent@0.4.3
├── uuid@3.2.1
├─┬ xml-loader@1.2.1
│ ├─┬ loader-utils@1.1.0
│ │ ├── big.js@3.2.0
│ │ ├── emojis-list@2.1.0
│ │ └── json5@0.5.1
│ └── xml2js@0.4.19 deduped
├─┬ xml2js@0.4.19
│ ├── sax@1.2.4
│ └── xmlbuilder@9.0.7
├── xmldom@0.1.27
└── xpath@0.0.23
```

**Comment by f3ist** [comment]
I did some logging too. My lambda gives back `node-fetch` as a function, while in your guys `pubcontrolclient.js` its returned as an object. The `global.fetch` is undefined.

Logs in my Lambda:
```
global.fetch undefined
typeof global.fetch: undefined
node-fetch: function Fetch(url, opts) { // removed remaining function definition output
typeof node-fetch: function
```

Logs in `pubcontrolclient.js`:
```
global.fetch: undefined
typeof global.fetch: undefined
node-fetch { Headers: [Getter],
  Request: [Getter],
  Response: [Getter],
  FetchError: [Getter],
  default: 
  { [Function: fetch]
  isRedirect: [Function],
  default: [Circular],
  Promise: [Function: Promise] } }
typeof node-fetch: object
// Obviously fetch and transport are equal to the node-fetch output
```

**Comment by jkarneges** [comment]
Two different return values for `require('node-fetch')` in the same project? That is super weird. Can you post the full source or a reduced version that replicates the issue?

**Comment by f3ist** [comment]
@jkarneges Very strange indeed, but only your library is affected and its related to the new release. Unfortunately I don't have time to put that together right now. I've locked the `pubcontrol` version to 1.1.1 and that continues to work for us. Please post back if you figure it out as we are paying Fanout customers.

**Comment by jkarneges** [comment]
It seems this is a known issue between node-fetch and webpack: https://github.com/bitinn/node-fetch/issues/450

The [last comment](https://github.com/bitinn/node-fetch/issues/450#issuecomment-387045223) on the above issue suggests a fix of simply appending `.default` to the require, and this should work in both webpack and non-webpack situations. Notably this approach is now being used by [Octokit](https://github.com/octokit/rest.js/pull/939/files).

I've tested this fix with and without webpack and it works for me. @f3ist can you change `require('node-fetch')` to `require('node-fetch').default` in pubcontrolclient.js to confirm it works for you too?

**Comment by f3ist** [comment]
@jkarneges I confirmed that adding `.default` resolves the issue. Thanks for digging deeper
